# Generated by Django 5.0.14 on 2025-12-01 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'answers',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_points', models.IntegerField(default=0)),
                ('earned_points', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer')], default='mcq', max_length=20)),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.IntegerField(default=30, help_text='Time limit in minutes, 0 for no limit')),
                ('passing_score', models.IntegerField(default=70, help_text='Passing score percentage')),
                ('randomize_questions', models.BooleanField(default=True)),
                ('show_answers_after_submission', models.BooleanField(default=True)),
                ('is_final_quiz', models.BooleanField(default=False)),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum attempts allowed, 0 for unlimited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
                'ordering': ['course', '-created_at'],
            },
        ),
    ]
