# Generated by Django 5.0.14 on 2025-12-01 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=200)),
                ('completion_date', models.DateField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verification_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-created_at'],
            },
        ),
    ]
